# Use the one in distributed-process.yml

language: c

sudo: false

matrix:
  include:
  - env: CABAL_INSTALL_VER=1.24 GHCVER=8.0.2 BUILD=cabal
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}


cache:
  directories:
  - $HOME/.cabal/packages

before_install:
# cabal case:
# workaround for https://ghc.haskell.org/trac/ghc/ticket/9221
# taken from https://github.com/hvr/multi-ghc-travis/blob/0fa68f78c2b1b059f904c9abc85510a3bb4f57e2/README.md
- case "$BUILD" in
    cabal)
      export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABAL_INSTALL_VER/bin:$HOME/.cabal/bin:$PATH;
      ghc --version;
      cabal --version;
      travis_retry cabal update;
      sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config
      ;;
  esac

install:
- case "$BUILD" in
    cabal)
      cabal install --jobs=2 --enable-tests --only-dependencies -ftcp . 
      ;;
  esac

script:
- case "$BUILD" in
    cabal)
      cabal install --jobs=2 --enable-tests -ftcp .
      cabal configure -ftcp --enable-tests;
      cabal build --jobs=2;
      export ARG='--test-options'
      export TEST_PACKAGE=""
      ;;
   esac
- $BUILD ${ARGS} test $ARG='--plain -t "!Flaky"' ${TEST_PACKAGE}TestCHInMemory
- $BUILD ${ARGS} test $ARG='--plain -t "!Flaky"' ${TEST_PACKAGE}TestCHInTCP
- $BUILD ${ARGS} test $ARG='--plain -t "!SpawnReconnect"' ${TEST_PACKAGE}TestClosure
- $BUILD ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestStats
- $BUILD ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestMx
- $BUILD ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestTracing
